name: Deploy to LWS cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Prepare files for deployment
        run: |
          echo "Vérification de la structure du dossier out/"
          ls -la out/
          
          echo "Création du fichier .htaccess..."
          cat > out/.htaccess << 'EOL'
          Options -MultiViews
          RewriteEngine On
          RewriteBase /
          
          # Forcer HTTPS
          RewriteCond %{HTTPS} off
          RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
          
          # Rediriger /en vers /en/
          RewriteCond %{REQUEST_URI} ^/en$
          RewriteRule ^(.*)$ $1/ [R=301,L]
          
          # Gérer les routes pour /en/contact
          RewriteCond %{REQUEST_URI} ^/en/contact/?$
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^en/contact/?$ /en/contact/index.html [L]
          
          # Gérer les routes pour /en/gallery
          RewriteCond %{REQUEST_URI} ^/en/gallery/?$
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^en/gallery/?$ /en/gallery/index.html [L]
          
          # Gérer les routes pour /fr/contact
          RewriteCond %{REQUEST_URI} ^/fr/contact/?$
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^fr/contact/?$ /fr/contact/index.html [L]
          
          # Gérer les routes pour /fr/gallery
          RewriteCond %{REQUEST_URI} ^/fr/gallery/?$
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^fr/gallery/?$ /fr/gallery/index.html [L]
          
          # Gérer les routes pour /contact
          RewriteCond %{REQUEST_URI} ^/contact/?$
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^contact/?$ /contact/index.html [L]
          
          # Gérer les routes pour /gallery
          RewriteCond %{REQUEST_URI} ^/gallery/?$
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^gallery/?$ /gallery/index.html [L]
          
          # Gérer les routes pour /en/
          RewriteCond %{REQUEST_URI} ^/en/
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^en/(.*)$ /en/index.html [L]
          
          # Gérer les routes pour /fr/
          RewriteCond %{REQUEST_URI} ^/fr/
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^fr/(.*)$ /fr/index.html [L]
          
          # Gérer les routes pour la racine
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^(.*)$ /index.html [L]
          
          # Enable CORS
          Header set Access-Control-Allow-Origin "*"
          Header set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
          Header set Access-Control-Allow-Headers "Content-Type, Authorization"
          
          # Compression
          <IfModule mod_deflate.c>
              AddOutputFilterByType DEFLATE text/plain
              AddOutputFilterByType DEFLATE text/html
              AddOutputFilterByType DEFLATE text/xml
              AddOutputFilterByType DEFLATE text/css
              AddOutputFilterByType DEFLATE application/xml
              AddOutputFilterByType DEFLATE application/xhtml+xml
              AddOutputFilterByType DEFLATE application/rss+xml
              AddOutputFilterByType DEFLATE application/javascript
              AddOutputFilterByType DEFLATE application/x-javascript
          </IfModule>
          
          # Cache Control
          <IfModule mod_expires.c>
              ExpiresActive On
              ExpiresByType image/jpg "access plus 1 year"
              ExpiresByType image/jpeg "access plus 1 year"
              ExpiresByType image/gif "access plus 1 year"
              ExpiresByType image/png "access plus 1 year"
              ExpiresByType text/css "access plus 1 month"
              ExpiresByType application/javascript "access plus 1 month"
          </IfModule>
          EOL
          
          echo "Structure finale des dossiers:"
          find out/ -type f

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Deploy to LWS cPanel
        run: |
          lftp -c "
            set ftp:ssl-allow false;
            set ftp:use-feat false;
            set net:max-retries 3;
            set net:timeout 30s;
            set mirror:parallel-directories true;
            set mirror:parallel-transfer-count 4;
            set mirror:parallel-chunk-size 1M;
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}:21;
            mirror --reverse --verbose=3 --parallel=4 --only-newer ./out/ ${{ secrets.FTP_SERVER_DIR }}/
          " 