name: Deploy to LWS cPanel

on:
  push:
    branches:
      - main  # ou master selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          npm run export
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Deploy to LWS cPanel
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: ${{ secrets.FTP_PASSWORD }}
          local_path: './out/*'
          remote_path: ${{ secrets.FTP_SERVER_DIR }}
          port: 21
          exclude: |
            .git*
            .env*
            .github*
            README.md
            .DS_Store 