name: Deploy to LWS cPanel

on:
  push:
    branches:
      - main  # ou master selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: List build output
        run: |
          echo "Contenu du dossier out/:"
          ls -la out/
          echo "Structure des dossiers:"
          find out/ -type f

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Deploy to LWS cPanel
        run: |
          lftp -c "
            set ftp:ssl-allow false;
            set ftp:use-feat false;
            set net:max-retries 3;
            set net:timeout 30s;
            set mirror:parallel-directories true;
            set mirror:parallel-transfer-count 4;
            set mirror:parallel-chunk-size 1M;
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}:21;
            mirror --reverse --verbose=3 --ignore-time --parallel=4 --only-newer ./out/ ${{ secrets.FTP_SERVER_DIR }}/
          " 