name: Deploy to LWS cPanel

on:
  push:
    branches:
      - main  # ou master selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          npm run export
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Deploy to LWS cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./out/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/.env*
            **/.github/**
            **/README.md
            **/.DS_Store 